### ISSUE TITLE
Compiling MGTEST

### ISSUE THREAD

**Issue by progfrosty** [JulStrat/puGUI#1]
Hello

I'm trying to compile MGTEST for Linux (on Ubuntu 20) with fpc.

I notice that I get the following error when I run the example:

An unhandled exception occurred at $00000000004010D7:
EAccessViolation: Access violation
  $00000000004010D7
  $00000000004259CD
  $00000000004258AB
  $000000000040117E

Compiling with fpc -B -I../ MGTEST.PAS

All compiles OK.

**Comment by JulStrat** [comment]
Hi, @progfrosty !

Sorry for delay.

Please check frame buffer device settings - `./fbset -v`
eg 
```
# fbset -v
Linux Frame Buffer Device Configuration Version 2.1 (23/06/1999)
(C) Copyright 1995-1999 by Geert Uytterhoeven

Opening frame buffer device `/dev/fb0'
Using current video mode from `/dev/fb0'

mode "1280x720"
    geometry 1280 720 1280 720 16
    timings 0 0 0 0 0 0 0
    accel true
    rgba 5/11,6/5,5/0,0/0
endmode
```
Next, set constants `fbdev` , `SCR_WIDTH`, `SCR_HEIGHT` in file `Linux/MGTEST.LPR` 
eg
```
const
  fbdev = '/dev/fb0';
  SCR_WIDTH = 1280;
  SCR_HEIGHT = 720;
```
 
Regards.
